language: node_js
node_js:
- '0.11'
before_install: 
install:
- npm install
before_script:
- npm link .
script:
- npm run test
- npm run cover
- npm run report
env:
  global:
    secure: RzNJxGMUdlkh5LSkySYSsrngQWsxWMtwgaVZtv7InvnPX1yeWA7gxxKrXCB2vnEh9ee73BwpnNEOyhIJglzS02prplHYPbRqpI9KmA1/jPYxAMDqxNKHxdlDgNgHuQfiaKFXQndLOpzU3/X1P3WiqmDfyf8M/mun4d5VEguHo4gd+89IOeZp/BzULFwYVPhv8mzR2nUCxXV1c3cOAj20fJKvrzkuBfR6XDhFo4lfm5HzsRIznFWAafOZfM5xNbW+F9h0Fju0/JyttzFPP3gn2I4mIzKPdZN41c5vu7XaK4SBAtUfq4H99t0bdffH3DYDTevvvmKXyAPbvxlYUTtvFpSlyYaG07yz90VobU0xHzt9RRGopEUFrxRjPM9z42dnnTkBQCLYvnn5kEv48UDG8nxXPRZZv3kiKso6FcZZoymZTNBUcpWwFbm1QamAQE7fY80qEorpc+UbSJWNwrxbW6uD0nZgBSywTzaFI6ydp50vXvqWIX0JyWSsfVNpnPkb1sT9A2lvyvW/dpzl6jtqqb5sUM9HJCHCXvglyVpFAOpQrIXzq2XwYrPwOYLa4eUxxZDEHtYuEBzjCyehy8y8iS0sSAYlLLR387O9Q30P699ZYhUQpvdYEU2Sq1VLFtxxCljlngAICvP4Sg+wWfnPvOGbYoJTQaPUYU14gXqgDq0=
